"""add isDisabled column to user table

Revision ID: 537c99d4dbea
Revises: c645f2bf2997
Create Date: 2023-11-02 23:55:37.474415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '537c99d4dbea'
down_revision: Union[str, None] = 'c645f2bf2997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isDisabled', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isDisabled')
    # ### end Alembic commands ###
