"""update for vendor

Revision ID: 849d8388b0f8
Revises: 279399d633c0
Create Date: 2023-10-01 16:32:56.376687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '849d8388b0f8'
down_revision: Union[str, None] = '279399d633c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menuitem', 'menuItemImage',
               existing_type=sa.BLOB(),
               type_=sa.String(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menuitem', 'menuItemImage',
               existing_type=sa.String(length=500),
               type_=sa.BLOB(),
               existing_nullable=True)
    # ### end Alembic commands ###
