"""added_complaint

Revision ID: c645f2bf2997
Revises: e8ac05b33347
Create Date: 2023-10-28 23:21:57.462280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c645f2bf2997'
down_revision: Union[str, None] = 'e8ac05b33347'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint',
    sa.Column('complaintID', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('comment', sa.String(length=100), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=False),
    sa.Column('roleID', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('createdtime', sa.DateTime, nullable=False),
    sa.PrimaryKeyConstraint('complaintID'),
    sa.ForeignKeyConstraint(['userID'], ['user.userID'], ),
    sa.ForeignKeyConstraint(['roleID'], ['role.roleID'], ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('complaint')
    # ### end Alembic commands ###
