"""add vendorProfileID and discountType for promotion

Revision ID: c8e2fef67180
Revises: 849d8388b0f8
Create Date: 2023-10-15 00:19:29.299576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8e2fef67180'
down_revision: Union[str, None] = '849d8388b0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promotion', sa.Column('discountType', sa.String(length=16), nullable=False))
    op.add_column('promotion', sa.Column('vendorProfileID', sa.Integer(), nullable=False))
    op.drop_index('promoCode', table_name='promotion')
    op.create_unique_constraint(None, 'promotion', ['promoCode', 'vendorProfileID'])
    op.create_foreign_key(None, 'promotion', 'vendor_profile', ['vendorProfileID'], ['vendorProfileID'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promotion', type_='foreignkey')
    op.drop_constraint(None, 'promotion', type_='unique')
    op.create_index('promoCode', 'promotion', ['promoCode'], unique=False)
    op.drop_column('promotion', 'vendorProfileID')
    op.drop_column('promotion', 'discountType')
    # ### end Alembic commands ###
