"""add shopDesc to vendorProfile

Revision ID: f1d7f4712a8c
Revises: 355d9fe2b688
Create Date: 2023-09-25 21:31:17.772018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1d7f4712a8c'
down_revision: Union[str, None] = '355d9fe2b688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_profile', sa.Column('shopDesc', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_profile', 'shopDesc')
    # ### end Alembic commands ###
