"""db init

Revision ID: fa28c036b808
Revises: 
Create Date: 2023-09-10 02:05:09.092666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa28c036b808'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('roleID', sa.Integer(), nullable=False),
    sa.Column('roleName', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('roleID')
    )
    op.create_table('user_profiles',
    sa.Column('profileID', sa.BINARY(length=16), nullable=False),
    sa.Column('profileName', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('profileID')
    )
    op.create_table('users',
    sa.Column('userID', sa.BINARY(length=16), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('userPassword', sa.String(length=50), nullable=False),
    sa.Column('roleID', sa.Integer(), nullable=False),
    sa.Column('profileID', sa.BINARY(length=16), nullable=False),
    sa.ForeignKeyConstraint(['profileID'], ['user_profiles.profileID'], ),
    sa.ForeignKeyConstraint(['roleID'], ['roles.roleID'], ),
    sa.PrimaryKeyConstraint('userID'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_profiles')
    op.drop_table('roles')
    # ### end Alembic commands ###
