name: Backend CI on Pull Request

on:
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'backend'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run pytest for unit testing
        run: |
          pytest app/test/

      - name: Get changed Python files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/dev...HEAD -- '*.py')
          echo "Changed py files:"
          echo "$CHANGED_FILES"
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Run pylint for linting
        run: |
          cd ..
          CHANGED_FILES="${{ steps.changed-files.outputs.changed_files }}"
          if [ -n "$CHANGED_FILES" ]; then
            echo "$CHANGED_FILES" | xargs pylint
          fi
      
      - name: Run Bandit for SAST
        run: |
          cd ..
          CHANGED_FILES="${{ steps.changed-files.outputs.changed_files }}"
          if [ -n "$CHANGED_FILES" ]; then
            echo "$CHANGED_FILES" | xargs bandit -c bandit.yaml -r
          fi
