name: Frontend CI/CD on Pull Request

on:
  pull_request:
    paths:
      - 'frontend/**' # Specify the path to your frontend code

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'frontend'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Use the version of Node.js you need

      - name: Install dependencies using pnpm
        run: |
          npm install -g pnpm # Install pnpm globally
          pnpm install
        working-directory: frontend

      - name: Build frontend
        run: pnpm run build # Adjust the build command to match your Vite.js setup

      - name: Run Unit Tests
        run: |
          # Run unit tests
          pnpm run test

      - name: Get changed tsx files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/dev...HEAD -- '*.tsx')
          echo "::set-output name=changed_files::$CHANGED_FILES"

      - name: Lint frontend code
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.changed_files }}"
          if [ -n "$CHANGED_FILES" ]; then
          echo "$CHANGED_FILES" | xargs pnpm run lint 
          fi

      - name: Run npm audit
        run: |
          CHANGED_FILES="${{ steps.changed-files.outputs.changed_files }}"
          if [ -n "$CHANGED_FILES" ]; then
          echo "$CHANGED_FILES" | xargs pnpm audit
          fi

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          java-version: 11 # Use the version of Java required by OWASP ZAP

      - name: Install and Run OWASP ZAP
        run: |
          # Download and install OWASP ZAP (replace with the actual download URL)
          wget -q https://github.com/zaproxy/zaproxy/releases/download/v2.11.0/ZAP_2.11.0_Linux.tar.gz -O frontend/zap.tar.gz
          tar -xzf frontend/zap.tar.gz
          cd frontend/ZAP_2.11.0
          ./zap.sh -daemon -port 8080

      - name: Run OWASP ZAP Scan
        run: |
          # Start your Vite.js application or server
          # Perform any necessary setup for your application (e.g., starting it on a specific port)
          # Run the ZAP spider and active scan
          ./zap-cli.py quick-scan -o reports/frontend/zap-report.html -l Medium --spider -r 'http://localhost:5173'  # Adjust the target URL and scan options
